config/routes.rb
Rails.application.routes.draw do

  get 'funs/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  resources :posts
  devise_for :users, controlles: { registrations: "registrations"}

  resources :events
  get 'events/index'
  get 'home/index'
  get 'home/sat'
   get 'home/event'
    get 'home/prayer'
     get 'home/testemony'
     get 'home/fun'
     get 'home/out'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:suject, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  if user_signed_in?
  	redirect_to posts_path
  else
  	redirect_to new_user_session_path
  end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

		private

		def sign_up_params
			params.require(:user).permit(:name, :email,:password, :password_confirmation)	
		end

		def account_update_params
			params.require(:user).permit(:name, :email,:password, :password_confirmation, :current_password)
			
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :suject %>
    <%= f.text_field :suject %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<div class="row">
<div class="container">
  <table>
    <thead>
 
      <tr>
        <th id="sujevent">Suject</th>
        
        <th>Description</th>
</div>

        <th colspan="8"></th>
      </tr>
    </thead>
  </p>


<tbody>
  <% @events.each do |event| %>
  <tr>
    <td><%= event.suject %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>

    <!--   authorization -->

    <% if event.user == current_user %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>



<div class="container">
<button>
<%= link_to 'New Event', new_event_path %>
</button>
<button style="margin-left:15px;">

<%= link_to 'Home', posts_path %>
</button>

</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>
<a href="home/index"></a>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suject:</strong>
  <%= @event.suject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'New Event', new_event_path %>
<%= link_to 'Back', events_path %>

app/views/home/event.html.erb
<div id="event">

<h3>Create an Event</h3>
<h5>Share your thought</h5>
<p>Plan something,you would like to do, with the people of to Lord. <br> Let's His name be glorify.</p>
<%= link_to 'New Event', new_event_path %>
</div>
<%= link_to 'See Create Event', events_path %>

app/views/home/fun.html.erb
<div class="fun">

	<h1 style="text-align:center;
	color:orange;">
	LET'S HAVE SOME FUN!!
</h1>
<aside>
	<h3>Life </h3>

</aside>
<div class="container">
	<hr>
	<div class="row">
		<div class="col m3.5">
			<%= image_tag("orlando1.jpg", :width => 350, :height => 450,)  %>

		</div>

		<div class="col s6">
			<p>NOVEMBER 4, 2016</p>
			<p style="font-size:18px;">
				Having the Orlando youth assembly with us was extremely a blessing. Words can’t really describe how much they blessed us in the service. The song they sang , they words the shared with God’s people was amazing. 
				
				We  all felt the  presence of the Lord was in the room.They were excited to be with us, we were encouraged by them. Their testimonies was living testimonies, you could see how much  the Love the lord, and how they seeking for the Lord. That allow us to know that we are not alone in this race; we all are fighting the good to make it. .</p>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col s9">
				<h4 style="color:orange">Just you </h4>
				
					<%= image_tag ("bible.jpg") %>
					<h4>Is it about you , or is really for God?</h4>
					<p>The Glory of God
Our first major goal is the glory of God. Our greatest concern is that His Name be great among the nations, from the rising to the setting of the sun (Malachi 1:11), and that the Lamb who was slain might receive the full reward for His sufferings (Revelation 7:9-10). We find our great purpose and motivation not in man or his needs, but in God, His commitment to His own glory, and our God-given desire to see Him worshipped in every nation, tribe, people, and language. We find our great confidence not in the Church’s ability to fulfill the Great Commission, but in God’s unlimited and unhindered power to accomplish all He has decreed. </p>
					</div>
					</div>
					<div class="row">
		<div class="col m3.5" style="margin-top:2em;">
					<%= image_tag("outactive.jpg", :width => 300, :height => 450,)  %>
					</div>

		<div class="col s7" style="margin-top:55px;">
			<h3>
What is your Goal?</h3>
				
				<p>Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.
				Whosoever therefore shall break one of these least commandments, and shall teach men so, he shall be called the least in the kingdom of heaven: but whosoever shall do and teach them, the same shall be called great in the kingdom of heaven.<br>Blessed are they which do hunger and thirst after righteousness: for they shall be filled.Ye are the salt of the earth: but if the salt have lost his savour, wherewith shall it be salted? it is thenceforth good for nothing, but to be cast out, and to be trodden under foot of men.</p>


			</div>

		</div>
	</div>



<div id="slideshow">
  <div class="section">
    <div class="slide" id="slide1"></div>
    <div class="slide" id="slide2"></div>
    <div class="slide" id="slide3"></div>
  </div>
</div>
</div>

<div id="sidebar">
  <div class="logo-container">
    <h1>LOGO</h1>
  </div>
  <div class="menu-container">
    <p>menu item1</p>
    <p>menu item2</p>
    <p>menu item3</p>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/out.html.erb
<h3>Stay Aware</h3>
<div class="row">
	<div class="container">

	<div class="col s6">
			<h3>TRIPS</h3>
			<h4>Where we going This year?</h4>
			
			<li>Texas meeting in FEB-2017</li>
			<li>BOC meeting in Jul-2017</li>
			<li>The nation trip in Summer-2017</li>
			<li>visit Local churchs</li>
		</div>

		<div class="col s6">
			<h3>LIVE FOR THE LORD</h3>
			<h4> Share the  Good Word!!</h4>
		</div>
	</div>
</div>


<div class="row">
	<div class="container">
	<div class="out">


			<div class="col s7">
			
				<%= image_tag("outactive.jpg", :width => 300, :height => 450,)  %>
				<p>
					ve others like you never love before. <br> 
					love everything 

				</p>
	
			</div>
	
		
		<div class="col s5">

			
				<%= image_tag("travel.jpg", :width => 300, :height => 450,)  %>
				<p>Go out with your brothers and sisters, share the Word of God<br>
					Love others like you never love before. <br> 

				</p>
			
		</div>
	</div>
	</div>
</div>


<div class="row">
	<div class="container">
	<div class="out">


			<div class="col s7">
			
				<%= image_tag("outactive.jpg", :width => 300, :height => 450,)  %>
				<p>
					ve others like you never love before. <br> 
					love everything 

				</p>
	
			</div>
	
		
		<div class="col s5">

			
				<%= image_tag("travel.jpg", :width => 300, :height => 450,)  %>
				<p>Go out with your brothers and sisters, share the Word of God<br>
					Love others like you never love before. <br> 

				</p>
			
		</div>
	</div>
	</div>
</div>

app/views/home/prayer.html.erb
<div class="container">
<h3 style="text-align:center;">Need A Prayer</h3> <p style="font-size:18px; text-align:center;"> Fill this form</p> 
<form action="https://formspree.io/phil9231@gmail.com"
          method="POST">
            <div class="row">
              <div class="small-12 medium-6 columns">
                <label>Your name</label>
                  <input type="text" placeholder=""/>
              </div>

              <div class="small-12 medium-6 columns">
                <label>Your email</label>
                  <input type="text" placeholder=""/>
              </div>

              
            </div>

            <div class="row">
              <div class="small-12 columns">
                <label>Your message</label>
                  <textarea placeholder=""></textarea>
              </div>
            </div>
            <input type="submit" value="Send">
            

          </form>
          <h5> I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;</h5>

          <%= image_tag ("bible.jpg") %>
          <p>But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;</p>

          
          </div>

app/views/home/sat.html.erb
<div class="satcourage">


	<div class="row">
		<div id="courage">
			<div class="col s5 ">
				<div class="card-panel teal">
					<span class="white-text">read about saturday service.relive the service in here, catch everything you miss.
					</span>
				</div>

			</div>
			<div class="row">
				<div class="col s8 m2">
					<div class="card-panel teal">
						<span class="white-text">The Word of God is sharper than anything.
						</span>
					</div>
				</div>
				<div class="row">
					<div class="col s5">
						<div class="card-panel teal">
							<span class="white-text">Even through the darkness,when don't see a way just have faith. 
							</span>
						</div>
					</div>
				</div>


			</div>

		</div>

	</div>
</div>

<h1 style="text-align:center;">Saturday Services</h1>
<div class="satmessa">
	<div class="container">
		<div class="satms" style="font-size:18px;">

			<p>
				After his conversion, Paul went to Damascus, where Acts 9 states he was healed of his blindness and baptized by Ananias of Damascus.[44] Paul says that it was in Damascus that he barely escaped death.[2 Cor. 11:32] Paul also says that he then went first to Arabia, and then came back to Damascus.[Gal. 1:17][45] Paul's trip to Arabia is not mentioned anywhere else in the Bible, and some suppose he actually traveled to Mount Sinai for meditations in the desert.[46][47] He describes in Galatians how three years after his conversion he went to Jerusalem. There he met James and stayed with Simon Peter for 15 days.[Gal. 1:13-24] Paul located Mount Sinai in Arabia in Galatians 4:24-25.

				Paul asserted that he received the Gospel not from man, but directly by "the revelation of Jesus Christ".[Gal 1:11-16] He claimed almost total independence from the Jerusalem community,[3]:pp.316–320 (possibly in the Cenacle), but agreed with it on the nature and content of the gospel.[Gal 1:22-24] He appeared eager to bring material support to Jerusalem from the various growing Gentile churches that he started. In his writings, Paul used the persecutions he endured to avow proximity and union with Jesus and as a validation of his teaching.

				Paul's narrative in Galatians states that 14 years after his conversion he went again to Jerusalem.[Gal. 2:1-10] It is not known what happened during this time, but both Acts and Galatians provide some details.[48] At the end of this time, Barnabas went to find Paul and brought him back to Antioch. [Acts 11:26]

				When a famine occurred in Judea, around 45–46,[49] Paul and Barnabas journeyed to Jerusalem to deliver financial support from the Antioch community.[50] According to Acts, Antioch had become an alternative center for Christians following the dispersion of the believers after the death of Stephen. It was in Antioch that the followers of Jesus were first called "Christians".
			</p>
			<h6>The Holy Word</h6>
			<p>The Glory of God
				Our first major goal is the glory of God. Our greatest concern is that His Name be great among the nations, from the rising to the setting of the sun (Malachi 1:11), and that the Lamb who was slain might receive the full reward for His sufferings (Revelation 7:9-10). We find our great purpose and motivation not in man or his needs, but in God, His commitment to His own glory, and our God-given desire to see Him worshipped in every nation, tribe, people, and language. We find our great confidence not in the Church’s ability to fulfill the Great Commission, but in God’s unlimited and unhindered power to accomplish all He has decreed. </p>
				<p>
					Paul asserted that he received the Gospel not from man, but directly by "the revelation of Jesus Christ".[Gal 1:11-16] He claimed almost total independence from the Jerusalem community,[3]:pp.316–320 (possibly in the Cenacle), but agreed with it on the nature and content of the gospel.[Gal 1:22-24] He appeared eager to bring material support to Jerusalem from the various growing Gentile churches that he started. In his writings, Paul used the persecutions he endured to avow proximity and union with Jesus and as a validation of his teaching.

				Paul's narrative in Galatians states that 14 years after his conversion he went again to Jerusalem.[Gal. 2:1-10] It is not known what happened during this time, but both Acts and Galatians provide some details.[48] At the end of this time, Barnabas went to find Paul and brought him back to Antioch. [Acts 11:26]

				</p>
			</div>
		</div>
	</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- Latest compiled and minified CSS -->
<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
          
   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
          

  <body>
  <% if user_signed_in? %>
  <%= current_user.name %>


<button class="waves-effect btn" style="background-color:#d7ccc8;">
<div id="signout">
   <%= link_to "Sign_out", destroy_user_session_path, :method => 'delete' %>

  
   </div>
  </button> 
  <button class="waves-effect btn" style="background-color:#d7ccc8;">

    <%= link_to 'Home', posts_path %>
     </button>
  
   <br>

  <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="fullpage">



  <!--     user interac part of page. -->


  <hr width="75%"; color=" orange";>

  <div class="row">
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
         <%= image_tag("note.jpg", :width => 10, :height => 450,)  %>
         <span class="card-title">Saturday's services</span>
       </div>
       <div class="card-content">
        <p>Read and relive Saturday's service.See what you missed.</p>
      </div>
      <div class="card-action">
        <a href="home/sat">Saturday's Services</a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
         <%= image_tag("outactive.jpg", :width => 10, :height => 450,)  %>
         <span class="card-title">FUN NIGHT</span>
       </div>
       <div class="card-content">
        <p>Enjoy life, live it to the fullest everyday. Spend time and have fun with your brothers and sisterss</p>
      </div>
      <div class="card-action">
        <a href="home/fun">FUN NIGHT</a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
         <%= image_tag("travel.jpg", :width => 10, :height => 450,)  %>
         <span class="card-title">TRAVEL</span>
       </div>
       <div class="card-content">
        <p>Go out, and share the gospel! Fellowship with other churches in the Body of Christ. Get out of your comfort zone and testify what God has done for you. </p>
      </div>
      <div class="card-action">

        <a href="home/out">Activities</a>
      </div>
    </div>

  </div>

</div>

</div>
<hr width="75%" color=" orange";>




<div class="">
  <div class="row"> 
    <!-- the message of sunday -->

    <div class="col s12" style="text-align:center;font-family:Trebuchet"><h1>SUNDAY SERVICE</h1>
    </div>
    <div class="col s6"><h3 style="text-align:center;font-family:impact">THE MESSAGE</h3><br><p style="font-size:20px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of
      Where does it come from?
      Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

      The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 f 

      It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

      It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

    </div>

    <!--  the key message -->


    <div class="col s4">
      <h3>  KEY OF THE MESSAGE</h3>
      <div id="keyms">
        <li ">Lorem Ipsum is simply dummy .</li><br>

        <li>c typesetting, remaining essentially unchanged.versions of 
          Where does it come from?</li><br>
          <li>  Lorem Ipsum has been the industry'secimen book </li><br>
          <li>c typesetting, remaining essentially unchanged.versions of 
            Where does it come from?</li><br>
            ere does it come from?</li><br>
            <li>c typesetting, remaining essentially unchanged.versions of 
              Where does it come from?</li><br>
            </div>
            <br>
            <div class="row">
              <div class="col s12 m9">
                <div class="card">
                  <div class="card-image">
                   <%= image_tag("prayer1.jpg", :width => 10, :height => 250,)  %>
                   <span class="card-title">NEED A PRAYER</span>
                 </div>
                 <div class="card-content">
                  <p>Prayer is the key that can open any door. Whatever it is that you may be going through. God can make a way, where there seems to be none. Prayer is also thee # 1 way to stay connected to Him. request a prayer.
.</p>
                  </div>
                  <div class="card-action">
                    <a href="home/prayer">Need a prayer</a>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col s12 m8">
                  <div class="card">
                    <div class="card-image">
                     <%= image_tag("event1.jpg", :width => 10, :height => 250,)  %>
                     <span class="card-title">Events</span>
                   </div>
                   <div class="card-content">
                    <p>Organize a memorable event that will leave a lasting impression on your brothers and sisters in the Lord.
</p>
                    </div>
                    <div class="card-action">
                      <a href="home/event">c  reate An Event</a>
                    </div>
                  </div>
                </div>
              </div>  
            </div>  
          </div>
        </div>


      </div>
    <!--   image with description -->

     <div class="image-box">
  <div class="image-container">
    <img width="200" height="150" src="http://lorempixel.com/200/150/food/1" alt="Food">
  </div>
  <div class="image-details">
    <h4>Lorem Ipsum</h4>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna...</p>
  </div>
</div>

<div class="image-box">
  <div class="image-container">
    <img width="200" height="150" src="http://lorempixel.com/200/150/food/2" alt="Food">
  </div>
  <div class="image-details">
    <h4>Lorem Ipsum</h4>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna...</p>
  </div>
</div>



      <!--   post and create new post here. -->

      <div class="col s12 m7">
        <div class="postpg">
          <p id="notice"><%= notice %></p>
          <div id="encourag">gof
            <h4>Words of encouragement</h4>

            <table>
              <thead>
                <tr>
                 <div class="row">
                   <div class="container">
                    <div class="col s7">
                      <th style="font-size:35px;color:orange;font-family:impact;">Title</th>
                    </div>
                    <div class="col s5">
                      <th style="font-size:45px; color:orange;font-family:impact;padding-left:50px;">Content</th>
                    </div>

                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @posts.each do |post| %>
                  <tr>
                    <td class="title"><%= post.title %></td><br/>

                    <td class="content"><br /><%= post.content %></td><br>
                    <td></td></td>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>

            <br>
          </div>

          <%= link_to 'New Post', new_post_path %>
        </div>
      </div>   
    </div>
  </div>

app/views/posts/show.html.erb
<div class="row">
<div class="col s18 m2">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<p id="notice"><%= notice %></p>
				<span class="card-title">
					<p>
						<strong>Title:</strong>
						<%= @post.title %>
					</p>
				</span>
				<p>
					<strong>Content:</strong>
					<%= @post.content %>
				</p>
				<div class="card-action">
					<%= link_to 'Edit', edit_post_path(@post) %> |
					<%= link_to 'Back', posts_path %>
				</div>
			</div>
		</div>
	</div>